### ISSUE TITLE
Health scaling calculations are wrong.

### ISSUE THREAD

**Issue by AntoineDehan** [ArsenicPurple/BossHealthMod#1]
Hi,

I don't understand all of your calculations but they are wrong.
 https://github.com/ArsenicPurple/BossHealthMod/blob/f44d4b6cdd555e29f24ab2ffb46b5137e104391f/src/main/java/co/basin/betterbosses/MultiplayerBosses.java#L53C25-L53C70

If I wanted to increase the health of boses by 15% for example, it will increase by 85% per your calculations.
I've been using your mod in my newest update and some people find bosses with 40k+ health even though they have like 300 by default.

**Comment by Lyllittle** [comment]
https://github.com/ArsenicPurple/BossHealthMod/blob/main/src/main/java/co/basin/betterbosses/MultiplayerBosses.java#L53

Correct line 53 should be:
`double scalar = (playerCount - 1) * Config.multiplierPerPlayer;`

**Comment by ArsenicPurple** [comment]
Thank you for letting me know. Sorry for getting to this so late. I have fixed the issue as of 1.1.2
