### ISSUE TITLE
Lists of boss entities and loot bag tints always get reset to default when starting game

### ISSUE THREAD

**Issue by NeuTraLZero** [ArsenicPurple/BossHealthMod#3]
Title.
When I add more bosses to the list and start Minecraft as normal, the lists in the config get reset back to default with only vanilla, cataclysm and BOMD bosses

Mod version: 1.1.1
Forge 1.20.1 47.3.11

**Comment by ArsenicPurple** [comment]
Thanks! Fixed as of version 1.1.2
